name: Run Biome

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v5
      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: .tool-versions
          cache: yarn      
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: Biome check
        run: yarn biome ci .